name: fastapi
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - fastapi==0.85.0
  - uvicorn[standard]==0.18.3
  - sqlalchemy==1.4.41
  - python-jose[cryptography]==3.3.0
  - python-dotenv==0.21.0
  - pyotp==2.7.0
  - yagmail==0.15.293
  - passlib[bcrypt]==1.7.4
  - rsa==4.9
  - pip:
      - psycopg2==2.9.4
